### ISSUE TITLE
Add functionality for `/component/fault-injection/platform-blocked-fault`

### ISSUE THREAD

**Issue by antonykamp** [BP2022-AP1/bp2022-ap1#449] opened 2023-05-11 06:54 UTC
## User stories
As a user I want add a platform blocked fault configuration and get all my platofrm blocked fault configurations in order to administrate them.

## Dependencies
Depends on: 
 - #99 
 - #102 
 - #100 

## Acceptance Criteria
- [ ] Implement POST `/component/fault-injection/platoform-blocked-fault` path
- [ ] Implement GET `/component/fault-injection/platform-blocked-fault` path

**Comment by instant-sky** [comment] 2023-05-11 09:39
duplicate of #446

**Closed as not planned by instant-sky** 2023-05-11 09:39 UTC
Labels: duplicate, Prio 3, 8, Functional
