### ISSUE TITLE
Implement abstract Component Class

### ISSUE THREAD

**Issue by CR1337** [BP2022-AP1/bp2022-ap1#35] opened 2023-03-16 10:47 UTC
## User stories
We need an abstract Component class that is able to subscribe to the TraCi Wrapper. It can be used as inheritable interface for all our components that need to get notified when the Wrapper made a step.

## Acceptance Criteria
- [ ] Implement abstract Interface

**Comment by Lietze** [comment] 2023-03-16 12:24
Duplicate of #32

**Closed by Lietze** 2023-03-16 12:24 UTC
Labels: duplicate, Needs Prio, Needs Estimation, Functional
